// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: market.proto

package server

import (
	"context"

	"dex/market/internal/logic"
	"dex/market/internal/svc"
	"dex/market/market"
)

type MarketServer struct {
	svcCtx *svc.ServiceContext
	market.UnimplementedMarketServer
}

func NewMarketServer(svcCtx *svc.ServiceContext) *MarketServer {
	return &MarketServer{
		svcCtx: svcCtx,
	}
}

func (s *MarketServer) GetRecentTrades(ctx context.Context, in *market.GetRecentTradesRequest) (*market.GetRecentTradesResponse, error) {
	l := logic.NewGetRecentTradesLogic(ctx, s.svcCtx)
	return l.GetRecentTrades(in)
}

func (s *MarketServer) GetPumpTokenList(ctx context.Context, in *market.GetPumpTokenListRequest) (*market.GetPumpTokenListResponse, error) {
	l := logic.NewGetPumpTokenListLogic(ctx, s.svcCtx)
	return l.GetPumpTokenList(in)
}

func (s *MarketServer) GetClmmPoolList(ctx context.Context, in *market.GetClmmPoolListRequest) (*market.GetClmmPoolListResponse, error) {
	l := logic.NewGetClmmPoolListLogic(ctx, s.svcCtx)
	return l.GetClmmPoolList(in)
}

func (s *MarketServer) GetKline(ctx context.Context, in *market.GetKlineRequest) (*market.GetKlineResponse, error) {
	l := logic.NewGetKlineLogic(ctx, s.svcCtx)
	return l.GetKline(in)
}

func (s *MarketServer) GetPairInfoByToken(ctx context.Context, in *market.GetPairInfoByTokenRequest) (*market.GetPairInfoByTokenResponse, error) {
	l := logic.NewGetPairInfoByTokenLogic(ctx, s.svcCtx)
	return l.GetPairInfoByToken(in)
}

func (s *MarketServer) GetNativeTokenPrice(ctx context.Context, in *market.GetNativeTokenPriceRequest) (*market.GetNativeTokenPriceResponse, error) {
	l := logic.NewGetNativeTokenPriceLogic(ctx, s.svcCtx)
	return l.GetNativeTokenPrice(in)
}

func (s *MarketServer) PushTokenInfo(ctx context.Context, in *market.PushTokenInfoRequest) (*market.PushTokenInfoResponse, error) {
	l := logic.NewPushTokenInfoLogic(ctx, s.svcCtx)
	return l.PushTokenInfo(in)
}

func (s *MarketServer) GetTokenInfo(ctx context.Context, in *market.GetTokenInfoRequest) (*market.GetTokenInfoResponse, error) {
	l := logic.NewGetTokenInfoLogic(ctx, s.svcCtx)
	return l.GetTokenInfo(in)
}

func (s *MarketServer) TokenSecurityCheck(ctx context.Context, in *market.TokenSecurityCheckRequest) (*market.TokenSecurityCheckResponse, error) {
	l := logic.NewTokenSecurityCheckLogic(ctx)
	return l.TokenSecurityCheck(in)
}

func (s *MarketServer) GetUserTokens(ctx context.Context, in *market.GetUserTokensRequest) (*market.GetUserTokensResponse, error) {
	l := logic.NewGetUserTokensLogic(ctx, s.svcCtx)
	return l.GetUserTokens(in)
}

func (s *MarketServer) GetUserPools(ctx context.Context, in *market.GetUserPoolsRequest) (*market.GetUserPoolsResponse, error) {
	l := logic.NewGetUserPoolsLogic(ctx, s.svcCtx)
	return l.GetUserPools(in)
}

func (s *MarketServer) RecordUserAsset(ctx context.Context, in *market.RecordUserAssetRequest) (*market.RecordUserAssetResponse, error) {
	l := logic.NewRecordUserAssetLogic(ctx, s.svcCtx)
	return l.RecordUserAsset(in)
}
