// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: market.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Market_GetPumpTokenList_FullMethodName    = "/market.Market/GetPumpTokenList"
	Market_GetClmmPoolList_FullMethodName     = "/market.Market/GetClmmPoolList"
	Market_GetKline_FullMethodName            = "/market.Market/GetKline"
	Market_GetPairInfoByToken_FullMethodName  = "/market.Market/GetPairInfoByToken"
	Market_GetNativeTokenPrice_FullMethodName = "/market.Market/GetNativeTokenPrice"
	Market_PushTokenInfo_FullMethodName       = "/market.Market/PushTokenInfo"
	Market_GetTokenInfo_FullMethodName        = "/market.Market/GetTokenInfo"
	Market_TokenSecurityCheck_FullMethodName  = "/market.Market/TokenSecurityCheck"
	Market_GetUserTokens_FullMethodName       = "/market.Market/GetUserTokens"
	Market_GetUserPools_FullMethodName        = "/market.Market/GetUserPools"
	Market_RecordUserAsset_FullMethodName     = "/market.Market/RecordUserAsset"
)

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketClient interface {
	GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error)
	GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error)
	GetKline(ctx context.Context, in *GetKlineRequest, opts ...grpc.CallOption) (*GetKlineResponse, error)
	GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
	GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
	PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error)
	GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
	TokenSecurityCheck(ctx context.Context, in *TokenSecurityCheckRequest, opts ...grpc.CallOption) (*TokenSecurityCheckResponse, error)
	GetUserTokens(ctx context.Context, in *GetUserTokensRequest, opts ...grpc.CallOption) (*GetUserTokensResponse, error)
	GetUserPools(ctx context.Context, in *GetUserPoolsRequest, opts ...grpc.CallOption) (*GetUserPoolsResponse, error)
	RecordUserAsset(ctx context.Context, in *RecordUserAssetRequest, opts ...grpc.CallOption) (*RecordUserAssetResponse, error)
}

type marketClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketClient(cc grpc.ClientConnInterface) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPumpTokenListResponse)
	err := c.cc.Invoke(ctx, Market_GetPumpTokenList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClmmPoolListResponse)
	err := c.cc.Invoke(ctx, Market_GetClmmPoolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetKline(ctx context.Context, in *GetKlineRequest, opts ...grpc.CallOption) (*GetKlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKlineResponse)
	err := c.cc.Invoke(ctx, Market_GetKline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPairInfoByTokenResponse)
	err := c.cc.Invoke(ctx, Market_GetPairInfoByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNativeTokenPriceResponse)
	err := c.cc.Invoke(ctx, Market_GetNativeTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushTokenInfoResponse)
	err := c.cc.Invoke(ctx, Market_PushTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenInfoResponse)
	err := c.cc.Invoke(ctx, Market_GetTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) TokenSecurityCheck(ctx context.Context, in *TokenSecurityCheckRequest, opts ...grpc.CallOption) (*TokenSecurityCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenSecurityCheckResponse)
	err := c.cc.Invoke(ctx, Market_TokenSecurityCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetUserTokens(ctx context.Context, in *GetUserTokensRequest, opts ...grpc.CallOption) (*GetUserTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTokensResponse)
	err := c.cc.Invoke(ctx, Market_GetUserTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetUserPools(ctx context.Context, in *GetUserPoolsRequest, opts ...grpc.CallOption) (*GetUserPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPoolsResponse)
	err := c.cc.Invoke(ctx, Market_GetUserPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) RecordUserAsset(ctx context.Context, in *RecordUserAssetRequest, opts ...grpc.CallOption) (*RecordUserAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordUserAssetResponse)
	err := c.cc.Invoke(ctx, Market_RecordUserAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
// All implementations must embed UnimplementedMarketServer
// for forward compatibility.
type MarketServer interface {
	GetPumpTokenList(context.Context, *GetPumpTokenListRequest) (*GetPumpTokenListResponse, error)
	GetClmmPoolList(context.Context, *GetClmmPoolListRequest) (*GetClmmPoolListResponse, error)
	GetKline(context.Context, *GetKlineRequest) (*GetKlineResponse, error)
	GetPairInfoByToken(context.Context, *GetPairInfoByTokenRequest) (*GetPairInfoByTokenResponse, error)
	GetNativeTokenPrice(context.Context, *GetNativeTokenPriceRequest) (*GetNativeTokenPriceResponse, error)
	PushTokenInfo(context.Context, *PushTokenInfoRequest) (*PushTokenInfoResponse, error)
	GetTokenInfo(context.Context, *GetTokenInfoRequest) (*GetTokenInfoResponse, error)
	TokenSecurityCheck(context.Context, *TokenSecurityCheckRequest) (*TokenSecurityCheckResponse, error)
	GetUserTokens(context.Context, *GetUserTokensRequest) (*GetUserTokensResponse, error)
	GetUserPools(context.Context, *GetUserPoolsRequest) (*GetUserPoolsResponse, error)
	RecordUserAsset(context.Context, *RecordUserAssetRequest) (*RecordUserAssetResponse, error)
	mustEmbedUnimplementedMarketServer()
}

// UnimplementedMarketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServer struct{}

func (UnimplementedMarketServer) GetPumpTokenList(context.Context, *GetPumpTokenListRequest) (*GetPumpTokenListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPumpTokenList not implemented")
}
func (UnimplementedMarketServer) GetClmmPoolList(context.Context, *GetClmmPoolListRequest) (*GetClmmPoolListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClmmPoolList not implemented")
}
func (UnimplementedMarketServer) GetKline(context.Context, *GetKlineRequest) (*GetKlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKline not implemented")
}
func (UnimplementedMarketServer) GetPairInfoByToken(context.Context, *GetPairInfoByTokenRequest) (*GetPairInfoByTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPairInfoByToken not implemented")
}
func (UnimplementedMarketServer) GetNativeTokenPrice(context.Context, *GetNativeTokenPriceRequest) (*GetNativeTokenPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNativeTokenPrice not implemented")
}
func (UnimplementedMarketServer) PushTokenInfo(context.Context, *PushTokenInfoRequest) (*PushTokenInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushTokenInfo not implemented")
}
func (UnimplementedMarketServer) GetTokenInfo(context.Context, *GetTokenInfoRequest) (*GetTokenInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenInfo not implemented")
}
func (UnimplementedMarketServer) TokenSecurityCheck(context.Context, *TokenSecurityCheckRequest) (*TokenSecurityCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TokenSecurityCheck not implemented")
}
func (UnimplementedMarketServer) GetUserTokens(context.Context, *GetUserTokensRequest) (*GetUserTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTokens not implemented")
}
func (UnimplementedMarketServer) GetUserPools(context.Context, *GetUserPoolsRequest) (*GetUserPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPools not implemented")
}
func (UnimplementedMarketServer) RecordUserAsset(context.Context, *RecordUserAssetRequest) (*RecordUserAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordUserAsset not implemented")
}
func (UnimplementedMarketServer) mustEmbedUnimplementedMarketServer() {}
func (UnimplementedMarketServer) testEmbeddedByValue()                {}

// UnsafeMarketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServer will
// result in compilation errors.
type UnsafeMarketServer interface {
	mustEmbedUnimplementedMarketServer()
}

func RegisterMarketServer(s grpc.ServiceRegistrar, srv MarketServer) {
	// If the following call panics, it indicates UnimplementedMarketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Market_ServiceDesc, srv)
}

func _Market_GetPumpTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPumpTokenListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetPumpTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetPumpTokenList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetPumpTokenList(ctx, req.(*GetPumpTokenListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetClmmPoolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClmmPoolListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetClmmPoolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetClmmPoolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetClmmPoolList(ctx, req.(*GetClmmPoolListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetKline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetKline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetKline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetKline(ctx, req.(*GetKlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetPairInfoByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPairInfoByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetPairInfoByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetPairInfoByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetPairInfoByToken(ctx, req.(*GetPairInfoByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetNativeTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNativeTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetNativeTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetNativeTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetNativeTokenPrice(ctx, req.(*GetNativeTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_PushTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).PushTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_PushTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).PushTokenInfo(ctx, req.(*PushTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetTokenInfo(ctx, req.(*GetTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_TokenSecurityCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenSecurityCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).TokenSecurityCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_TokenSecurityCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).TokenSecurityCheck(ctx, req.(*TokenSecurityCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetUserTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetUserTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetUserTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetUserTokens(ctx, req.(*GetUserTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetUserPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetUserPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetUserPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetUserPools(ctx, req.(*GetUserPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_RecordUserAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordUserAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).RecordUserAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_RecordUserAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).RecordUserAsset(ctx, req.(*RecordUserAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Market_ServiceDesc is the grpc.ServiceDesc for Market service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Market_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPumpTokenList",
			Handler:    _Market_GetPumpTokenList_Handler,
		},
		{
			MethodName: "GetClmmPoolList",
			Handler:    _Market_GetClmmPoolList_Handler,
		},
		{
			MethodName: "GetKline",
			Handler:    _Market_GetKline_Handler,
		},
		{
			MethodName: "GetPairInfoByToken",
			Handler:    _Market_GetPairInfoByToken_Handler,
		},
		{
			MethodName: "GetNativeTokenPrice",
			Handler:    _Market_GetNativeTokenPrice_Handler,
		},
		{
			MethodName: "PushTokenInfo",
			Handler:    _Market_PushTokenInfo_Handler,
		},
		{
			MethodName: "GetTokenInfo",
			Handler:    _Market_GetTokenInfo_Handler,
		},
		{
			MethodName: "TokenSecurityCheck",
			Handler:    _Market_TokenSecurityCheck_Handler,
		},
		{
			MethodName: "GetUserTokens",
			Handler:    _Market_GetUserTokens_Handler,
		},
		{
			MethodName: "GetUserPools",
			Handler:    _Market_GetUserPools_Handler,
		},
		{
			MethodName: "RecordUserAsset",
			Handler:    _Market_RecordUserAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}
